### ISSUE TITLE
[BUG] Images not scaled exactly to 80x80 pixels, Stream Deck Mini will not display

### ISSUE THREAD

**Issue by dhollinger** [magicmonkey/go-streamdeck#31]
**Describe the bug**
When using an image larger than the Stream Deck mini's key size (80x80), then the image doesn't apply

**Streamdeck version**
Mini (6 buttons)

**To Reproduce**

Create new Image File Button and launch the go program
```go
func (s *Screenshot) Buttons() {
    // Command
    myButton, err := buttons.NewImageFileButton(viper.GetString("buttons.images") + "/screenshot.png")
    if err != nil {
        log.Error().Err(err).Msg("Could not load image")
    }

    shotaction := &sdactionhandlers.CustomAction{}
    shotaction.SetHandler(func(btn streamdeck.Button) {
        go takeScreenshot()
    })
    myButton.SetActionHandler(shotaction)
    s.SD.AddButton(s.ButtonId, myButton)
}
```
**Expected behavior**
Image should resize, rotate, and display regardless of size.

**Environment (please complete the following information):**
 - OS: Pop!_OS 20.10
 - Go version: 1.14.13 (from ASDF)

**Comment by magicmonkey** [comment]
Thanks for the report, I'd used the wrong image dimensions.  Should be fixed now via @lornajane's PR.
